### ISSUE TITLE
SatispayIntent.ApiStatus.from return error for last version 9087

### ISSUE THREAD

**Issue by dommy1985** [satispay/satispayintent-android-sdk#4]
Hi I'm receiving  an error with last satispay-app-dev (Version 3.20.0-DEBUG (9087)) , in particular I'm using SatispayIntent.payChargeId with token of my backend, everything go well app is open and I can approve payment but when go back inside `onActivityResult` the `apiStatus.isValidRequest()` is false the message is `UNKNOWN: Old Satispay app? Wrong appPackage? Other reason?` but the payment go well because is present on transaction  my be also can complete payment , if I use an previous version of app everything go well , the problem seems are also on prod version , I tested with sample app and with my implementation ad have same error.

**Comment by andreborud** [comment]
Thanks for reporting this issue. We're looking into it!

**Comment by andreborud** [comment]
This should be fixed now in Version 3.21.0-DEBUG (9090) which is available now.
